name: system_tasks_dart
description: Get a list of system processes, and you can kill, start, restart a process
version: 0.2.0
homepage: https://github.com/januwA/system_tasks_dart.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  process_run: ^0.12.3+2
  path: ^1.8.2

dev_dependencies:
  test: ^1.6.0
